blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	path('home/', views.home_page, name='home_page'),
	path('posts/', views.post_list_view, name='post_list'),
    path('saved/', views.saved_posts_view, name='saved_posts'),
	path('posts/<int:pk>/', views.post_details_view, name='post_details'),
	path('edit/posts/<int:post_id>/', views.edit_post, name='edit_post'),
	path('create/post/', views.create_post, name='create_post'),
	path('post/<int:post_id>/comment/', views.add_comment_view, name='add_comment'),
    path('comment/<int:comment_id>/reply/', views.add_reply_to_comment_view, name='comment_reply'),
    path('save/post/', views.save_post, name='save_post'),
    path('unsave/post/<int:post_id>/', views.unsave_post, name='unsave_post'),
]

dviz_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Post


info_dict = {
    'queryset': Post.objects.all()
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {
        'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}
        }, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from accounts.models import UserAccount
from datetime import datetime
from taggit.managers import TaggableManager
from django.utils.text import slugify

class Post(models.Model):
	author = models.ForeignKey(UserAccount, related_name='posts', on_delete=models.CASCADE)
	title = models.CharField(max_length=500)
	image = models.FileField(upload_to=f"post-images {datetime.now().strftime('%Y-%m-%d')}", null=True, blank=True)
	image_caption_link = models.URLField(null=True, blank=True)
	image_caption_text = models.CharField(max_length=200, null=True, blank=True)
	body = models.TextField()
	slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
	date_published = models.DateTimeField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	tags = TaggableManager()

	def __str__(self):
		return f"{self.title} created by {self.author.username}"

	# overriding save method, to populate slug on title before saving...
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return f"/blog/posts/{self.id}/"

class Comment(models.Model):
	user = models.ForeignKey(UserAccount, related_name='comments', on_delete=models.CASCADE)
	post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
	text = models.TextField()
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f"Comment on {self.post.title}"

class CommentReply(models.Model):
	reply_to = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE)
	content      = models.TextField()
	reply_by     = models.ForeignKey(UserAccount, null=True, on_delete=models.CASCADE)
	active       = models.BooleanField(default=True) 
	date_created = models.DateField(auto_now_add=True)
	date_updated = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.reply_by.username} replied to {self.reply_to.user.username} on {self.reply_to}"
		
	class Meta:
		verbose_name_plural = 'Comments Replies'

class SavedPost(models.Model):
	post = models.ForeignKey(Post, related_name='saved_by', on_delete=models.CASCADE)
	author = models.ForeignKey(UserAccount, related_name='saved_posts', on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.post.title} Saved by {self.author.username}"
		
	class Meta:
		verbose_name_plural = 'Saved Posts'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>{% block title %} {% endblock %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Adil Saleem Khan">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/monokai-sublime.min.css">

    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %}">

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">Adil's Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="{{ request.user.image.url }}" alt="image" >			
					
					<div class="bio mb-3">{{ request.user.bio }}</div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a target="_blank" href="{{ request.user.twitter }}"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a target="_blank" href="{{ request.user.linkedin }}"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a target="_blank" href="{{ request.user.github }}"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a target="_blank" href="{{ request.user.instagram }}"><i class="fab fa-instagram fa-fw"></i></a></li>
			        </ul>
			        <hr> 
				</div>
				
				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item active">
					    <a class="nav-link" href="{% url 'blog:home_page' %}"><i class="fas fa-home fa-fw mr-2"></i>Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="{% url 'blog:saved_posts' %}"><i class="fas fa-bookmark fa-fw mr-2"></i>Saved Posts</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="#"><i class="fas fa-user fa-fw mr-2"></i>About Me</a>
					</li>
				</ul>
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
    	{% block headsection %}
		    
	    {% endblock %}
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container">

		    	{% block content %}

		    	{% endblock %}
				
		    </div>
	    </section>
	    
	    <footer class="footer text-center py-2 theme-bg-dark">
            <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Adil Saleem</a> for developers</small>		   
	    </footer>
    </div>    
    
    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->  
    <div id="config-panel" class="config-panel d-none d-lg-block">
        <div class="panel-inner">
            <a id="config-trigger" class="config-trigger config-panel-hide text-center" href="#"><i class="fas fa-cog fa-spin mx-auto" data-fa-transform="down-6" ></i></a>
            <h5 class="panel-title">Choose Colour</h5>
            <ul id="color-options" class="list-inline mb-0">
                <li class="theme-1 active list-inline-item"><a data-style="assets/css/theme-1.css" href="#"></a></li>
                <li class="theme-2  list-inline-item"><a data-style="{% static 'assets/css/theme-2.css' %}" href="#"></a></li>
                <li class="theme-3  list-inline-item"><a data-style="{% static 'assets/css/theme-3.css' %}" href="#"></a></li>
                <li class="theme-4  list-inline-item"><a data-style="{% static 'assets/css/theme-4.css' %}" href="#"></a></li>
                <li class="theme-5  list-inline-item"><a data-style="{% static 'assets/css/theme-5.css' %}" href="#"></a></li>
                <li class="theme-6  list-inline-item"><a data-style="{% static 'assets/css/theme-6.css' %}" href="#"></a></li>
                <li class="theme-7  list-inline-item"><a data-style="{% static 'assets/css/theme-7.css' %}" href="#"></a></li>
                <li class="theme-8  list-inline-item"><a data-style="{% static 'assets/css/theme-8.css' %}" href="#"></a></li>
            </ul>
            <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
        </div><!--//panel-inner-->
    </div><!--//configure-panel-->

    
       
    <!-- Javascript -->          
    <script src="{% static 'assets/plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script> 
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script> 

    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'assets/js/demo/style-switcher.js' %}"></script>     
    

</body>
</html> 

templates/cms_base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<title>{% block title %} {% endblock %}</title>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">Adil's Blog</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'blog:post_list' %}">CMS <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'blog:create_post' %}">Create Post</a>
	      </li>
	    </ul>
	  </div>
	</nav>

	<div class="container mt-5">
		{% block content %}

		{% endblock %}
	</div>
</body>
</html>

templates/comments.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/comments.css' %}">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<div class="container mb-5 mt-5">
	<div class="card">
		<div class="row">
			<div class="col-md-12">
				<h3 class="text-center mb-5">
					Comments ({{ comments.count }})
				</h3>

				<div class="row text-center" style="width: 100%;">
					<form id="comment_form" method="post" class="w-100">
						{% csrf_token %}
						<input type="text" name="comment_text" style="display: inline-block;" placeholder="share your thoughts" class="form-control w-75">
						<button type="submit" class="btn btn-primary">Add</button>
					</form>
				</div>
				<br>
				<div class="row">
					<div class="col-md-12" id="comments_list">
						{% for comment in comments %}
						<div class="media mb-5">
							<img class="mr-3 rounded-circle" alt="Bootstrap Media Preview"
								src="{{ comment.user.image.url }}" />
							<div class="media-body">
								<div class="row">
									<div class="col-8 d-flex">
										<h5>{{ comment.user.username }}</h5>
										<span>- 2 hours ago</span>
									</div>

									<div class="col-4" style="text-align:right;">
										<!-- <div class="reply">
											<a href="#"><span><i class="fa fa-reply"></i> reply</span></a>
										</div> -->
									</div>
								</div>
								{{ comment.text }}

								<!-- Reply portion -->

							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	document.querySelector("#comment_form").addEventListener('submit', (event) => {
		event.preventDefault();
		// let url = `http://127.0.0.1:8000/blog/comment/${comment_id}/reply/`
		let url =`http://127.0.0.1:8000/blog/post/{{ post_id }}/comment/`;
		let text = event.target.comment_text.value;

		const data = new FormData();
    	data.append('csrfmiddlewaretoken', "{{ csrf_token }}");
    	data.append('comment', text);

		var xhttp = new XMLHttpRequest();

		xhttp.onreadystatechange = function() {
			if (this.readyState == 4 && this.status == 200) {
				var results = JSON.parse(this.responseText);
				console.log(results);

				let new_comment = document.createElement('div');
				new_comment.className = 'media';
				new_comment.innerHTML = `
				<div class="media mb-5">
					<img class="mr-3 rounded-circle" alt="Bootstrap Media Preview"
						src="${results['image']}" />
					<div class="media-body">
						<div class="row">
							<div class="col-8 d-flex">
								<h5>${results['author']}</h5>
								<span>${results['date']}</span>
							</div>

							<div class="col-4" style="text-align:right;">
								
							</div>
						</div>
						${results['text']}
					</div>
				</div>
				`;
				document.querySelector("#comments_list").appendChild(new_comment);
				event.target.reset();
			}
		};

		xhttp.open("POST", url, true);
		xhttp.send(data);
	})
</script>

templates/home_page.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block headsection %}
	<section class="cta-section theme-bg-light py-5">
	    <div class="container text-center">
		    <h2 class="heading">DevBlog - A Blog Made For Developers</h2>
		    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
		    <form class="signup-form form-inline justify-content-center pt-3">
                <div class="form-group">
                    <label class="sr-only" for="semail">Your email</label>
                    <input type="email" id="semail" name="semail1" class="form-control mr-md-1 semail" placeholder="Enter email">
                </div>
                <button type="submit" class="btn btn-primary">Subscribe</button>
            </form>
	    </div><!--//container-->
    </section>
{% endblock %}

{% block content %}

	{% for post in posts %}
		<div class="item mb-5">
		    <div class="media">
			    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="{{ post.image.url }}" alt="image">
			    <div class="media-body">
				    <h3 class="title mb-1"><a href="{% url 'blog:post_details' post.id %}">{{ post.title }}</a></h3>
				    <div class="meta mb-1"><span class="date">Published {{ post.created.date }}</span><span class="time">5 min read</span><span class="comment"><a href="#">{{ post.comments.count }} comments</a></span></div>
				    <div class="intro">{{ post.body|truncatewords:35 }}</div>
				    <a class="more-link" href="{% url 'blog:post_details' post.id %}">Read more &rarr;</a>
			    </div>
		    </div>
	    </div>
    {% endfor %}
    
    <nav class="blog-nav nav nav-justified my-5">
	  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
	  <a class="nav-link-next nav-item nav-link rounded" href="blog-list.html">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
	</nav>
{% endblock %}

templates/login_form.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}
	<h2>
		Welcome to <b>D-viz</b> Blog....
	</h2>
	<hr>
	<h5>Login to your account please.</h5>
	<br>
	<form method="POST" action=".">
		{% csrf_token %}
	  <div class="mb-3">
	    <label for="exampleInputUsername1" class="form-label">Username</label>
	    <input type="text" class="form-control w-50" name="username" id="exampleInputUsername1">
	  </div>
	  <div class="mb-3">
	    <label for="exampleInputPassword1" class="form-label">Password</label>
	    <input type="password" name="password" class="form-control w-50" id="exampleInputPassword1">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	</form>
{% endblock %}

templates/post_details.html
{% extends "base.html" %}
{% load social_share %}
{% load static %}
{% load markdown_extras %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
	<header class="blog-post-header">
	    <h2 class="title mb-2">{{ post.title }}</h2>
	    <div class="meta mb-3"><span class="date">Published {{ post.created.date }}</span><span class="time">5 min read</span><span class="comment"><a href="#">{{ post.comments.count }} comments</a></span></div>
    </header>

    <div class="blog-post-body">
	    <figure class="blog-banner">
	        <a href="https://made4dev.com"><img class="img-fluid" src="{{ post.image.url }}" alt="image"></a>
	        <figcaption class="mt-2 text-center image-caption">
	        	Image Credit: <a href="https://made4dev.com?ref=devblog" target="_blank">made4dev.com (Premium Programming T-shirts)</a>
	        </figcaption>
	    </figure>
	    <br>
	    {{ post.body|markdown|safe }}
	</div>

	
	{% if request.user != post.author and not post|saved:request.user %}
		<button class="btn btn-sm btn-success" id="save-post-btn">Save</button>
	{% endif %}
	{% post_to_linkedin request.build_absolute_uri  %} 
	<br>

	{% include "comments.html" with comments=post.comments.all post_id=post.id ctoken=csrf_token %}

	<br>

	<section class="promo-section theme-bg-light py-5 text-center">
	    <div class="container">
		    <h2 class="title">Promo Section Heading</h2>
		    <p>You can use this section to promote your side projects etc. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. </p>
            <figure class="promo-figure">
		        <a href="https://made4dev.com" target="_blank"><img class="img-fluid" src="{% static 'assets/images/promo-banner.jpg' %}" alt="image"></a>
		    </figure>
	    </div>
    </section>

	<script>
		document.querySelector("#save-post-btn").addEventListener("click", (event) => {
			event.preventDefault();

			let url =`http://127.0.0.1:8000/blog/save/post/`;

			const data = new FormData();
			data.append('csrfmiddlewaretoken', "{{ csrf_token }}");
			data.append('post_id', "{{ post.id }}");

			var xhttp = new XMLHttpRequest();

			xhttp.onreadystatechange = function() {
				if (this.readyState == 4 && this.status == 200) {
					var results = JSON.parse(this.responseText);
					console.log(results["message"]);
				}
			}

			xhttp.open("POST", url, true);
			xhttp.send(data);
		})
	</script>
{% endblock %}

templates/post_form.html
{% extends "cms_base.html" %}

{% block title %} Post Creation {% endblock %}

{% block content %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
	<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

	<h4>
		{% if instance %}
			Edit Post
		{% else %}
			Create New Post
		{% endif %}
	</h4>
	<br>

	<form method="POST" action="." enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.media }}
		{{ form.as_p }}
		<p><input type="submit" value="{% if instance %}Edit{% else %}Create{% endif %}"></p>
	</form>	

	<script type="text/javascript">
		var simplemde = new SimpleMDE({
		    autofocus: true,
		    blockStyles: {
		      bold: "__",
		      italic: "_"
		    },
		    element: document.getElementById("id_body"),
		    forceSync: true,
		    indentWithTabs: false,
		    insertTexts: {
		      horizontalRule: ["", "\n\n-----\n\n"],
		      image: ["![](http://", ")"],
		      link: ["[", "](http://)"],
		      table: ["", "\n\n| Column 1 | Column 2 | Column 3 |\n| -------- | -------- | -------- |\n| Text     | Text      | Text     |\n\n"],
		    },
		    lineWrapping: true,
		    parsingConfig: {
		      allowAtxHeaderWithoutSpace: true,
		      strikethrough: false,
		      underscoresBreakWords: true,
		    },
		    placeholder: "Provide text content here...",
		    previewRender: function(plainText) {
		      return customMarkdownParser(plainText); // Returns HTML from a custom parser
		    },
		    previewRender: function(plainText, preview) { // Async method
		      setTimeout(function(){
		        preview.innerHTML = customMarkdownParser(plainText);
		      }, 250);

		      return "Loading...";
		    },
		    promptURLs: true,
		    renderingConfig: {
		      singleLineBreaks: false,
		      codeSyntaxHighlighting: true,
		    },
		    shortcuts: {
		      drawTable: "Cmd-Alt-T"
		    },
		    showIcons: ["code", "table"],
		    spellChecker: false,
		    status: false,
		    status: ["autosave", "lines", "words", "cursor"], // Optional usage
		    status: ["autosave", "lines", "words", "cursor", {
		      className: "keystrokes",
		      defaultValue: function(el) {
		        this.keystrokes = 0;
		        el.innerHTML = "0 Keystrokes";
		      },
		      onUpdate: function(el) {
		        el.innerHTML = ++this.keystrokes + " Keystrokes";
		      }
		    }], // Another optional usage, with a custom status bar item that counts keystrokes
		    tabSize: 4,
		  });
		document.querySelector('#id_title').className = "form-control";
		document.querySelector('#id_title').placeholder = "What this post is about...";
	</script>
{% endblock %}

templates/post_list.html
{% extends "cms_base.html" %}

{% block title %} Post Creation {% endblock %}

{% block content %}
	<h3>Created Posts</h3>
	<br>
	<div class="row">
		{% for post in posts %}

			<div class="col col-md-3 card ml-3">
				<img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
				<div class="card-body">
					<h5 class="card-title">{{ post.title }}</h5>
    				<p class="card-text">{{ post.body|truncatewords:10 }}</p>
    				<a href="{% url 'blog:edit_post' post.id %}" class="btn btn-sm btn-primary">Edit</a>
				</div>
			</div>

		{% endfor %}
	</div>

{% endblock %}

templates/post_saved.html
{% extends "base.html" %}

{% block title %} Saved Posts {% endblock %}

{% block content %}
	<h3>Saved Posts</h3>
	<br>
	<div class="row">
		{% for data in posts %}

			<div class="col col-md-5 card ml-3">
				<img class="card-img-top" src="{{ data.post.image.url }}" alt="Card image cap">
				<div class="card-body">
					<h5 class="card-title">{{ data.post.title }}</h5>
    				<p class="card-text">{{ data.post.body|truncatewords:10 }}</p>
    				<a href="{% url 'blog:unsave_post' data.post.id %}" class="btn btn-sm btn-danger">delete</a>
				</div>
			</div>

		{% endfor %}
	</div>

{% endblock %}

templates/signup_form.html
{% extends "base.html" %}

{% block title %} SignUp {% endblock %}

{% block content %}
	<h2>
		Welcome to <b>D-viz</b> Blog....
	</h2>
	<hr>
	<h5>SignUp for an Account.</h5>
	<br>
	<form method="POST" action=".">
		{% csrf_token %}
	  <div class="mb-3">
	    <label for="exampleInputUsername1" class="form-label">Username</label>
	    <input type="text" class="form-control w-50" name="username" id="exampleInputUsername1">
	    <small id="username-feedback"></small>
	  </div>
	  <div class="mb-3">
	    <label for="exampleInputEmail1" class="form-label">Email</label>
	    <input type="email" class="form-control w-50" name="email" id="exampleInputEmail1">
	  </div>

	  <div class="mb-3">
	    <label for="exampleInputPassword1" class="form-label">Password</label>
	    <input type="password" name="password" class="form-control w-50" id="exampleInputPassword1">
	  </div>

	  <div class="mb-3">
	    <label for="exampleInputPassword2" class="form-label">Confirm Password</label>
	    <input type="password" name="conf_password" class="form-control w-50" id="exampleInputPassword2">
	  </div>

	  <button type="submit" class="btn btn-primary">SignUp</button>
	</form>

	<script type="text/javascript">
		document.querySelector('#exampleInputUsername1').addEventListener('focusout', validateUsername);

		function validateUsername(event){
			event.preventDefault();
			const username = event.target.value;

			if (username === "") {
				// if username is empty, dont send request to BACKEND...
				return 
			}

			const url = `/accounts/validate/${username}/`;

			var xhttp = new XMLHttpRequest();

			xhttp.onreadystatechange = function () {
				if (this.readyState == 4 && this.status == 200) {
					const resp = JSON.parse(this.responseText);

					var feedback = document.querySelector('#username-feedback');

					if (resp["used"]) {
						feedback.className = 'text-danger';
						feedback.textContent = 'Username already taken';
					} else {
						feedback.className = 'text-success';
						feedback.textContent = 'Username available';
					}
				}
			}; 

			xhttp.open('GET', url, true);
			xhttp.send();
		}

	</script>
{% endblock %}